### ISSUE TITLE
right handles' alignment problem

### ISSUE THREAD

**Issue by szkrd** [champloo11/ng-easy-image-crop#5]
Right handles (top, middle, bottom) use percentage left, what was the problem with right+px? With percentage it's inaccurate, especially with smaller values (visible to the naked eye).

`#resize_top_right { top:-3px; left: 99.5%; cursor: ne-resize; }`

**Comment by szkrd** [comment]
Well, in fact all of the handles are misaligned (except maybe top left). Use negative margins, like this:

``` css
#resize_middle_left {
    top: 50%;
    margin-top: -3px;
    left: -3px;
    cursor: ew-resize;
}
```

It should look something like this:
![screen shot 2015-07-02 at 17 05 29](https://cloud.githubusercontent.com/assets/1073260/8480253/f9c63b52-20dc-11e5-8ede-1ffe6119d71e.png)
